project_id = "vwonynqoybfvaleyfmog"

[functions.create-student]
verify_jwt = false

[functions.ifthenpay-multibanco]
verify_jwt = true

[functions.ifthenpay-mbway]
verify_jwt = true

[functions.ifthenpay-webhook]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = true

[functions.notify-staff-activation]
verify_jwt = true
