project_id = "vwonynqoybfvaleyfmog"

[functions.create-student]
verify_jwt = false

[functions.ifthenpay-multibanco]
verify_jwt = true

[functions.ifthenpay-mbway]
verify_jwt = true

[functions.ifthenpay-webhook]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = true

[functions.notify-staff-activation]
verify_jwt = true

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code-and-register]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.send-password-reset-code]
verify_jwt = false

[functions.verify-password-reset]
verify_jwt = false
